:CSname: openEO
:Title: openEO Community Standard Work Item Justification
:titletext: openEO Community Standard
:doctype: community-standard
:encoding: utf-8
:lang: en
:toc:
:toc-placement!:
:toclevels: 4
:numbered:
:sectanchors:
:source-highlighter: pygments

<<<
[cols = ">",frame = "none",grid = "none"]
|===
|{set:cellbgcolor:#FFFFFF}
|[big]*Open Geospatial Consortium*
|Submission Date: 2024-03-07
|Approval Date:   <yyyy-mm-dd>
|Internal reference number of this OGC(R) document:    YY-nnnrx
|Category: OGC(R) Community Standard Work Item Justification
|Authors:   openEO Project Steering Committee
|===

[cols = "^", frame = "none"]
|===
|[big]*{titletext}*
|===

[cols = "^", frame = "none", grid = "none"]
|===
|*Copyright notice*
|Copyright (C) 2023 Open Geospatial Consortium
|To obtain additional rights of use, visit http://www.opengeospatial.org/legal/
|===

<<<

== Introduction

This document provides a justification to the OGC Technical Committee (TC) for consideration of {CSname} as a Community Standard. This justification, along with the submitted candidate Community Standard, will form the basis for TC review and vote to approve the start of a Work Item as the first step in the Community Standard process for this Standard.

The submitters agree to abide by the TC Policies and Procedures and OGC Intellectual Property Rights Policy (http://www.opengeospatial.org/ogc/policies) during the processing of this submission.

Once approved, the Community Standard Work Item defined by this document is valid for six (6) months.

== Overview of proposed submission

openEO specifies an open application programming interface (API) for connecting applications and other client software to big Earth observation cloud back-ends in a simple and unified way.

The openEO specification aims at increasing the interoperability of big EO data processing of satellite imagery in the cloud. Implementations of openEO can be used to add an interoperability layer on top of existing services.
Its development has been driven by the need to overcome the challenges associated with different tools, APIs, and data formats in geospatial technology. openEO has been developed from the bottom up, with each version of the specification supported by implementations.

The primary use case for specifying openEO was to simplify and unify the data processing using a common API and a specification for a set of pre-defined processes. As such, users can still work in their favored programming language without worrying about data organization and pre-processing. Users can avoid vendor lock-in as the generated process descriptions can be executed at multiple provider endpoints, making it easier to compare and reproduce processing results between different providers.

The specification consists of two parts:
* The openEO API, an HTTP API description specified as an OpenAPI document
* The openEO Processes, a set of requirements for pre-defined processes conforming to the openEO API specification

The openEO specification is openly licensed, governed and maintained.
The specification is released under the Apache 2.0 license and is publicly available via GitHub.
The project is governed by a Project Steering Committee: https://openeo.org/psc/

== Relationship to other OGC Standards

The openEO API builds on top of other standards and specifications and reuses other standards whenever possible.
openEO's basis is HTTP with JSON as request and response encoding.
The API specification reuses building blocks from the OGC API – Common Standard.
openEO adheres to the STAC API specification, which is based on the OGC API – Features Standard.
openEO allows the exposure of a wide variety of visualization and download services using existing standards/specifications including OGC WMS, OGC WMTS, OGC WFS, OGC WCS, OGC API – Tiles, OGC API – Maps, OGC API – Features, and XYZ.
For Authentication the openEO API uses the commonly used standards HTTP Basic (RFC 7617) and OpenID Connect.

== Alignment with OGC Standards Baseline

The openEO API aligns with the OGC APIs Standard baseline (especially OGC API – Common) and STAC. The openEO API standard fits well within the OGC API roadmap. 

OGC API – Processes and the openEO API are schematically similar with regards to processes and batch jobs and complement each other for these parts.
The specification caters for different user audiences: openEO API comes out of the box with a wider scope of features, while OGC API - Processes only covers processing and additional features require the integration of other OGC API specifications.
openEO allows for a more user-centric and less technical approach to big EO cloud processing, backed by an extensive set of pre-defined processes and its ecosystem.
OGC API - Processes is a highly flexible API for executing any kind of processes on any kind of data with the caveats that get implied by this flexibility.
On the other hand, openEO makes a different trade-off prioritizing interoperability between different implementations over flexibility by prescribing data models and process schemas. Users compose their algorithms in an abstract way as graphs using the openEO processes and leave the concrete realization of the process graph to the server implementation.
OGC API – Processes is more focused on executing concrete implementations of an algorithm, e.g. provided as application packages, without implying a specific data model.
Nevertheless, the openEO Processes could be used as a streamlined set of processes for OGC API – Processes.
OGC API – Processes is currently missing pre-defined processes for increased interoperability between implementations.
Additionally, work is ongoing to specify openEO user-defined processes as an encoding for OGC API – Processes - Part 3.

As requested by the reviewers, a detailed comparison of the openEO API and the OGC API - Processes has been compiled:
https://github.com/Open-EO/openeo-api/blob/ogcapi-processes/crosswalks/ogcapi-processes.md
If deemed useful, this could be the basis for further alignment in future versions of the specifications.

The openEO API is also considered as one building block for the emerging OGC GeoDataCube API Standard.

This specification enhances OGC operations and community involvement by providing a user-centric and less technical approach to big EO cloud processing, backed by an extensive set of pre-defined processes and a its surrounding ecosystem.

== Evidence of implementation

The openEO specification is backed by a considerably large ecosystem of open source servers, clients and tools.
The following is a list of publicly available implementations and deployments of the openEO specification.

Server deployments (9+):

* openEO Platform - https://openeo.cloud
* Copernicus Data Space Ecosystem - https://openeo.dataspace.copernicus.eu
* EODC - https://openeo.eodc.eu
* EURAC Research - https://openeo.eurac.edu
* Google Earth Engine (maintained by a third-party) - https://earthengine.openeo.org
* mundialis - https://openeo.mundialis.de
* Rasdaman - https://testbed19.rasdaman.com/rasdaman/openeo
* Sentinel Hub - https://openeo.sentinel-hub.com/production
* VITO - https://openeo.vito.be

Client implementations (5+):

* JavaScript - https://github.com/open-EO/openeo-js-client
* Julia - https://github.com/open-EO/openeo-julia-client
* Python - https://github.com/open-EO/openeo-python-client
* R - https://github.com/open-EO/openeo-r-client
* Browser-based User Interface - https://github.com/open-EO/openeo-web-editor

All these implementations are developed as open source software, and can be found, along with further implementations, in https://github.com/open-EO.

Additionally, there are implementations and deployments that are not fully publicly available.
For example, the implementation by IBM Research is open source but is deployed internally within the IBM infrastructure: https://github.com/IBM/tensorlakehouse-openeo-driver

Although many of the implementations are maintained close to the specification, they are indepenant projects and would not be part of the community standard.

*Date of most recent version:*

* Version 1.2.0 of the openEO API was released on May 25, 2023.
* Version 1.2.0 of the openEO Processes was released on Dec 13, 2021.

*Implementation description:*

The openEO specification is an openly licensed, governed and maintained project.

The specification consists of two parts:
* openEO API: https://api.openeo.org/1.2.0/
* openEO Processes: https://processes.openeo.org/1.2.0/

The openEO API is accompanied by a separately versioned set of openEO process descriptions.

*Implementation URL:*

* openEO API: https://github.com/open-EO/openeo-api
* openEO Processes: https://github.com/open-EO/openeo-processes

*Is implementation complete?*

* [x] Yes
* [ ] No

== Public availability

Is the proposed Community standard currently publicly available?

* [x] Yes
* [ ] No

* Website and Documentation: https://openeo.org
* API specification: https://api.openeo.org/1.2.0/ and https://github.com/Open-EO/openeo-api
* Process specification: https://processes.openeo.org/1.2.0/ and https://github.com/Open-EO/openeo-processes

== Supporting OGC Members

* University of Münster - Institute for Geoinformatics
* Eurac Research
* VITO (Flemish Institute for Technological Research)
* GeoConnections - Natural Resources Canada
* EUMETSAT
* European Space Agency (ESA)
* EOX IT Services GmbH
* Telespazio VEGA UK Ltd
* Planet Labs PBC
* German Aerospace Center - DLR
* Matthias Mohr - Softwareentwicklung

== Intellectual Property Rights

Will the contributor retain intellectual property rights?

* [x] Yes - The specification is open source, released under Apache 2.0 license
* [ ] No

If yes, the contributor will be required to work with OGC staff to properly attribute the submitter’s intellectual property rights.

If no, the contributor will assign intellectual property rights to the OGC.
